# Generated by Django 3.0.6 on 2020-07-15 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('s3_key', models.TextField()),
                ('extension', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.TextField(blank=True, default='', null=True)),
                ('age', models.IntegerField(null=True)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Files')),
            ],
        ),
    ]
