# Generated by Django 3.0.6 on 2020-07-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_files_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
