# Generated by Django 3.0.6 on 2020-07-19 11:34

from django.db import migrations, models
import key2bliss.backends.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200719_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='photo',
            field=models.ImageField(null=True, storage=key2bliss.backends.storage_backends.UserMediaStorage(), upload_to=''),
        ),
    ]
